#!/bin/bash

project_name="ts2hls"
docker rm -f ${project_name}
docker build -t ${project_name} -f Dockerfile.alpine .
docker run \
  -d \
  -p 8080:80 \
  --restart always \
  -v $(pwd)/data:/data \
  -v /tmp/docker/${project_name}:/tmp \
  --name ${project_name} \
  ${project_name}
