#!/bin/bash

pid=$$

hls_dir="/tmp/htdocs/${hash}"

if [[ -d ${hls_dir} ]]
then
	exit
fi

mkdir -p ${hls_dir}

trap "rm -rf ${hls_dir}" EXIT

echo ${pid}>${hls_dir}/pid

count=0
while [[ "${count}" != "3" ]]
do
	let "count++"
	ffmpeg -re -y -user_agent "OnlineTvAppDroid" -i "${source}" -codec copy -f hls -hls_init_time 1 -hls_time 5 -hls_list_size 9 -hls_base_url "${REQUEST_SCHEME}://${HTTP_HOST}/${hash}/" -hls_flags omit_endlist -hls_flags delete_segments -strftime 1 -use_localtime 1 -hls_segment_filename "${hls_dir}/stream-%s.ts" "${hls_dir}/index.m3u8" >/dev/null 2>&1
done
