#!/bin/bash

hls_dir="/tmp/htdocs/${hash}"

mkdir -p ${hls_dir}

trap "rm -rf ${hls_dir}" EXIT

if [ "${type}" == "hls" ]
then
    ffmpeg -y -user_agent "OnlineTvAppDroid" -i "${source}" -preset ultrafast -g 25 -sc_threshold 0 -codec copy -f hls -hls_time 2 -hls_list_size 8 -hls_flags delete_segments+second_level_segment_index+round_durations -hls_base_url "/${hash}/" -strftime 1 -use_localtime 1 -hls_segment_filename "${hls_dir}/stream-%s-%%04d.ts" "${hls_dir}/index.m3u8" >${hls_dir}/ffmpeg.log 2>&1 &
elif [ "${type}" == "ts" ]
then
    ffmpeg -y -user_agent "OnlineTvAppDroid" -i "${source}" -preset ultrafast -g 25 -sc_threshold 0 -codec copy -f hls -hls_time 2 -hls_list_size 8 -hls_flags delete_segments+second_level_segment_index+round_durations -hls_base_url "/${hash}/" -strftime 1 -use_localtime 1 -hls_segment_filename "${hls_dir}/stream-%s-%%04d.ts" "${hls_dir}/index.m3u8" >${hls_dir}/ffmpeg.log 2>&1 &
else
    exit
fi

while true
do
    sleep 1
    lsof | grep "${hls_dir}/ffmpeg.log" >/dev/null || exit
done
