#!/bin/bash

while read line
do
  eval export ${line}
done<${REQUEST_BODY_FILE}

./includes/ffmpeg-background >/dev/null 2>&1 &

pid=$!

hls_dir="/tmp/htdocs/${hash}"

count=0
while [[ ! -f ${hls_dir}/index.m3u8 ]]
do
	let "count++"
	[[ "${count}" == "15" ]] && { error/403; kill ${pid}; exit; }
	sleep 1
done

cat ${hls_dir}/index.m3u8 | error/200


