#!/bin/bash

while read line
do
  eval export "${line}"
done<${REQUEST_BODY_FILE}

hls_dir="/tmp/htdocs/${hash}"

if [ -d ${hls_dir} ]
then
    cat ${hls_dir}/index.m3u8 | error/200
else
    ./ffmpeg-background >/dev/null 2>&1 &
    while [ ! -f ${hls_dir}/index.m3u8 ]
    do
	if [ -f "${hls_dir}/ffmpeg.log" ]
	then
	    process_info="$(lsof | grep "${hls_dir}/ffmpeg.log")"
	    if [ "${process_info}" == "" ]
	    then
		echo "Error starting ffmpeg process..." | error/403
		exit
	    fi
	fi
    done
    # return m3u8 index to client only if we have minimum 2 chunks
    chunks_count=0
    while [ "${chunks_count}" -lt "3" ]
    do
        chunks_count="$(grep '^/' ${hls_dir}/index.m3u8 | wc -l)"
        sleep 1
    done
    cat ${hls_dir}/index.m3u8 | error/200
fi

