#!/bin/bash

while read line
do
  eval export "${line}"
done<${REQUEST_BODY_FILE}

hls_dir="/tmp/htdocs/${hash}"

if [ -d ${hls_dir} ]
then
    cat ${hls_dir}/index.m3u8 | error/200
else
    ./ffmpeg-background >/dev/null 2>&1 &
    count=0
    while [ ! -f ${hls_dir}/index.m3u8 ]
    do
	let "count++"
	if [ "${count}" == "15" ]
	then
	    echo "Error starting ffmpeg process..." | error/403
	fi
	sleep 1
    done
    # return m3u8 index to client only if we have minimum 2 chunks
    chunks_count=0
    while [ "${chunks_count}" -lt "2" ]
    do
	chunks_count="$(cat ${hls_dir}/index.m3u8 | grep '^/' | wc -l)"
	sleep 1
    done
    cat ${hls_dir}/index.m3u8 | error/200
fi

