#!/bin/bash

while read line
do
  eval export "${line}"
done<${REQUEST_BODY_FILE}

hls_dir="/tmp/htdocs/${hash}"

kill $(lsof | grep "${hls_dir}/ffmpeg.log" | cut -f1 | xargs) || true

echo "0" | error/200
